### PR TITLE
hw/arm/xlnx-versal-virt: modify gem/phy DT nodes

### LINKED ISSUE #6: vxworks cadence GEM driver fails to bind to the ethernet node in the xlnx-versal-virt generated device tree
VxWorks fails to initialize the driver for cadence GEM on the xlnx-versal-virt machine.

### PR DESCRIPTION
**Pull request by ho28**
Modify the gem/phy device tree nodes so that VxWorks properly binds the genericPhy driver to the ethernet-phy DT node. Previously, the phy was represented using a fixed-link node that VxWorks does not parse properly.

The compatible string for the gem node has been modified from "cdns,zynqmp-gem" to "cdns,versal-gem". The VxWorks gem driver does not match "cdns,zynqmp-gem".

Note: VxWorks needs additional property "phy-mode" to properly bind the driver against "cdns,versal-gem".

### CODE REVIEW

File: hw/arm/xlnx-versal-virt.c [hunk 1]
```diff
@@ -276,15 +276,22 @@ static void fdt_add_canfd_nodes(VersalVirt *s)
...
-    char *name = g_strdup_printf("%s/fixed-link", gemname);
+    uint64_t addr = MM_GEM_PHY_OFF;
+    char *name = g_strdup_printf("%s/ethernet-phy@%" PRIx64, gemname, addr);
+    const char compat_phy[] = "genericPhy";
 
     qemu_fdt_add_subnode(s->fdt, name);
     qemu_fdt_setprop_cell(s->fdt, name, "phandle", phandle);
-    qemu_fdt_setprop(s->fdt, name, "full-duplex", NULL, 0);
-    qemu_fdt_setprop_cell(s->fdt, name, "speed", 1000);
+    qemu_fdt_setprop_cell(s->fdt, name, "fifo-depth", 0x01);
```
Comment (kay-ge) [inline hw/arm/xlnx-versal-virt.c]: Should there be #defines or other constant definitions for 0x01, 0a0a, 0x08, 0x03 (the various constants on this line through line 292)?

**Comment by calvincramer** [comment]
@ho28 can you show some test results? Manual is fine. I'm not too familiar with what the CI tests test, but it looked like generic arm and generic x86 64.

**Review by calvincramer — APPROVED** [review]
@ho28 showed it working live

File: hw/arm/xlnx-versal-virt.c (hunk 1 above)
Comment (ho28) [reply hw/arm/xlnx-versal-virt.c]: actually, it looks like these properties are not needed when initializing the genericPhy driver. I had borrowed them from the zynqmp device tree, but on the real hardware that phy binds to the tiTdPhy driver; on the qemu platform the phy is not fully implemented and vxworks falls back to the genericPhy driver.

i'll go ahead and remove these other properties since they have no meaning to the emulated phy.

**Comment by ho28** [comment]
I made the changes mentioned above, removed the unnecessary properties from the phy node.

I also did some additional reading on the reg property of the phy node. I was under the assumption previously that the reg field (0xc) specified an offset from the regs or ranges presented by the GEM. After consulting the device tree documentation, it turns out the reg field is simply the phy index when specified as a property of a phy. I modified the constants and fields as appropriate.
